### ISSUE TITLE
Train on multiple GPU

### ISSUE THREAD

**Issue by theophilefro** [ludvb/xfuse#12]
Hello,
Very interesting paper ! I would like to train the model on my own datasets and therefore I would like to know how I can run it using multiple GPUs. 

Many thanks

**Comment by ludvb** [comment]
Thanks for your interest in our paper!

Multi GPU training is currently not supported. It is definitely something that would be nice to have in the future, though. I'm not familiar with the API for distributed training in Pytorch, so I'm not sure exactly how this could be implemented. The Pytorch API seems mostly tailored for torch `Module`s, which could pose a problem for us (our parameters are not stored at the module level, for example). On the other hand, Pytorch appears to have quite good low-level primitives for interprocess communication (both an RPC and MPI style interface).

In the meantime, have you tried running on only a single GPU? We have generally found good success using a single GPU with 11 GB memory. Usually, we can fit a `patch_size` of 768 px and a `batch_size` of 3, which is typically sufficient for images of sizes around 2000x2000 px.

**Comment by theophilefro** [comment]
Thanks for your answer, 
I tried on a single GPU and it seemed to be sufficient. But I met an issue while training the model. I have 10x Space Ranger data so I used the convert visium function. Then during the training I had an issue of shape raised by tensorboard whereas I didn't launch it. Is it because of the convert visium function which has specifcity or I'm just missing something ?

Thanks for your time

**Comment by ludvb** [comment]
Thanks for reporting back! A shape issue sounds like a potential bug. A few questions:

- Do you still have the traceback from this incident, or do you remember what the error message said exactly (you may be able to find it in the `log` file inside the `--save-path`)?
- How long could you run the training before encountering the error? 
- Have you tried running the training again? If so, do you get the same error?
- Which version are you running of tensorboard and pytorch (can be checked with `pip show tensorboard torch`)

**Comment by theophilefro** [comment]
Hi thanks for the response,
- The error message said exactly "
".../.local/lib/python3.8/site-packages/torch/utils/tensorboard/_utils.py", line 76, in make_grid
    assert I.ndim == 4 and I.shape[1] == 3
AssertionError
"
- The training runs until the 1000 epoch and stops.
- I have the same error everytime I run it. At first, I had error in the 34 epochs (the same one) and then I reduced the scale factor and it works until 1000.
- tensorboard version 2.2.2 and torch 1.5.1

Hope this can help

**Comment by ludvb** [comment]
What is the value of `network_width` in your config file? I seem to be able to reproduce the error when `network_width` is less than 3. If you are using a higher value, we will have to do some more detective work. As a first step, do you still have the full stack trace? It should look something like the following:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ludvig/Projects/xfuse/xfuse/utility/utility.py", line 330, in _wrapped
    return f(*args, **kwargs)
  File "/home/ludvig/Projects/xfuse/xfuse/__main__.py", line 51, in _wrapped
    return f(*args, **kwargs)
  File "/home/ludvig/Projects/xfuse/xfuse/__main__.py", line 312, in run
    _run(
  File "/home/ludvig/Projects/xfuse/xfuse/run.py", line 144, in run
    train(epochs)
  File "/home/ludvig/Projects/xfuse/xfuse/train.py", line 110, in train
    elbo = _epoch(epoch=epoch)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 263, in _fn
    apply_stack(msg)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 198, in apply_stack
    default_process_message(msg)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 159, in default_process_message
    msg["value"] = msg["fn"](*msg["args"], **msg["kwargs"])
  File "/home/ludvig/Projects/xfuse/xfuse/train.py", line 90, in _epoch
    elbo.append(_step(x=to_device(x)))
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 263, in _fn
    apply_stack(msg)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 198, in apply_stack
    default_process_message(msg)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 159, in default_process_message
    msg["value"] = msg["fn"](*msg["args"], **msg["kwargs"])
  File "/home/ludvig/Projects/xfuse/xfuse/train.py", line 78, in _step
    return -pyro.infer.SVI(model.model, model.guide, optim, loss).step(x)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/infer/svi.py", line 128, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/infer/trace_elbo.py", line 126, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/infer/elbo.py", line 170, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/infer/trace_elbo.py", line 52, in _get_trace
    model_trace, guide_trace = get_importance_trace(
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/infer/enum.py", line 47, in get_importance_trace
    model_trace = poutine.trace(poutine.replay(model, trace=guide_trace),
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ludvig/Projects/xfuse/xfuse/model/xfuse.py", line 90, in model
    return {e: _go(self.get_experiment(e), x) for e, x in xs.items()}
  File "/home/ludvig/Projects/xfuse/xfuse/model/xfuse.py", line 90, in <dictcomp>
    return {e: _go(self.get_experiment(e), x) for e, x in xs.items()}
  File "/home/ludvig/Projects/xfuse/xfuse/model/xfuse.py", line 76, in _go
    zs = [
  File "/home/ludvig/Projects/xfuse/xfuse/model/xfuse.py", line 77, in <listcomp>
    p.sample(
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/primitives.py", line 113, in sample
    apply_stack(msg)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 201, in apply_stack
    frame._postprocess_message(msg)
  File "/home/ludvig/Projects/xfuse/xfuse/handlers/stats/stats_handler.py", line 76, in _postprocess_message
    self._handle(**msg)
  File "/home/ludvig/Projects/xfuse/xfuse/handlers/stats/latent.py", line 17, in _handle
    self.add_images(
  File "/home/ludvig/Projects/xfuse/xfuse/handlers/stats/stats_handler.py", line 37, in <lambda>
    lambda *args, **kwargs: method(
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 583, in add_images
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 302, in image
    tensor = convert_to_HWC(tensor, dataformats)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/torch/utils/tensorboard/_utils.py", line 107, in convert_to_HWC
    tensor_CHW = make_grid(tensor_NCHW)
  File "/home/ludvig/.cache/pypoetry/virtualenvs/xfuse-WbJYarOX-py3.8/lib/python3.8/site-packages/torch/utils/tensorboard/_utils.py", line 76, in make_grid
    assert I.ndim == 4 and I.shape[1] == 3
AssertionError
```

**Comment by theophilefro** [comment]
I have a `network_width` of 16. Yes I still have the tracebak, it looks quite the same as yours.

```
Traceback (most recent call last):
  File "/home/t_froment/.local/bin/xfuse", line 8, in <module>
    sys.exit(cli())
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/utility/utility.py", line 281, in _wrapped
    return f(*args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/__main__.py", line 51, in _wrapped
    return f(*args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/__main__.py", line 312, in run
    _run(
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/run.py", line 144, in run
    train(epochs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/train.py", line 110, in train
    elbo = _epoch(epoch=epoch)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 263, in _fn
    apply_stack(msg)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 198, in apply_stack
    default_process_message(msg)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 159, in default_process_message
    msg["value"] = msg["fn"](*msg["args"], **msg["kwargs"])
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/train.py", line 90, in _epoch
    elbo.append(_step(x=to_device(x)))
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 263, in _fn
    apply_stack(msg)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 198, in apply_stack
    default_process_message(msg)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 159, in default_process_message
    msg["value"] = msg["fn"](*msg["args"], **msg["kwargs"])
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/train.py", line 78, in _step
    return -pyro.infer.SVI(model.model, model.guide, optim, loss).step(x)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/infer/svi.py", line 128, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/infer/trace_elbo.py", line 126, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/infer/elbo.py", line 170, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/infer/trace_elbo.py", line 52, in _get_trace
    model_trace, guide_trace = get_importance_trace(
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/infer/enum.py", line 47, in get_importance_trace
    model_trace = poutine.trace(poutine.replay(model, trace=guide_trace),
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/model/xfuse.py", line 90, in model
    return {e: _go(self.get_experiment(e), x) for e, x in xs.items()}
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/model/xfuse.py", line 90, in <dictcomp>
    return {e: _go(self.get_experiment(e), x) for e, x in xs.items()}
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/model/xfuse.py", line 88, in _go
    return experiment.model(x, zs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/model/experiment/st/st.py", line 389, in model
    image_distr = self._sample_image(x, decoded)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/model/experiment/image.py", line 184, in _sample_image
    pyro.sample(
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/primitives.py", line 113, in sample
    apply_stack(msg)
  File "/home/t_froment/.local/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 201, in apply_stack
    frame._postprocess_message(msg)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/handlers/stats/stats_handler.py", line 76, in _postprocess_message
    self._handle(**msg)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/handlers/stats/image.py", line 15, in _handle
    self.add_images("image/ground_truth", (1 + value) / 2)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/handlers/stats/stats_handler.py", line 37, in <lambda>
    lambda *args, **kwargs: method(
  File "/home/t_froment/.local/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 583, in add_images
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/home/t_froment/.local/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 302, in image
    tensor = convert_to_HWC(tensor, dataformats)
  File "/home/t_froment/.local/lib/python3.8/site-packages/torch/utils/tensorboard/_utils.py", line 107, in convert_to_HWC
    tensor_CHW = make_grid(tensor_NCHW)
  File "/home/t_froment/.local/lib/python3.8/site-packages/torch/utils/tensorboard/_utils.py", line 76, in make_grid
    assert I.ndim == 4 and I.shape[1] == 3
AssertionError
```

**Comment by ludvb** [comment]
Thanks! From the traceback, I'm guessing that the H&E image that you are using may have an alpha channel, which xfuse didn't expect. Could you check if that is the case? For example, if you have imagemagick, you can run

```
magick identify -format "%[channels]\n" /path/to/image
```

or open the image in something like Photoshop or Gimp and check the image properties.

**Comment by theophilefro** [comment]
Thanks! This was the issue indeed. But when I solve it removing the alpha channel, I have another error at the same epoch (1000). I don't really understand what it is due to.

```
Traceback (most recent call last):
  File "/home/t_froment/.local/bin/xfuse", line 8, in <module>
    sys.exit(cli())
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/t_froment/anaconda3/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/utility/utility.py", line 281, in _wrapped
    return f(*args, **kwargs)
  File "/home/t_froment/.local/lib/python3.8/site-packages/xfuse/session/session.py", line 65, in __exit__
    assert self == _SESSION_STACK.pop()
AssertionError
```

Thanks for your time and your answer and sorry to bother you.

**Comment by ludvb** [comment]
The traceback indicates a problem when exiting a session context. There may be another exception before this happens. Can you check if there are any more tracebacks before the one you posted? Is there a "session panic" message somewhere in the log file?

Sorry for all the trouble getting this to run, will definitely put some effort into polishing the user experience.

**Comment by theophilefro** [comment]
Yes the problem come from ```  CUDA out of memory. Tried to allocate...   ```. So I tried again diminishing the `batch_size` to `1` and I have the same error. Does the function torch.cuda.empty_cache() is used after the processing of each batch ?

**Comment by theophilefro** [comment]
I am not sure but I don't think Pytorch call it automatically.
I decreased the `network_depth` and `network_width`. The `batch_size` is set to `2` as you recommanded. The training seems to work.

Thanks for your time and answer.

**Comment by ludvb** [comment]
Awesome! Fingers crossed that the rest of the run will be smooth :)

**Comment by theophilefro** [comment]
Hi,

The rest of the run was great and i had the result I wanted. Now that the model is trained I would like to predict the gene expression on an unseen sample. I only have new image data (but related to the same tumor), and I would like to know how is it possible to run the analyses (metagenes and genes) on it.

Thanks.

**Comment by ludvb** [comment]
Awesome! I've created a patch for converting images without any associated expression data. Would be cool if you'd like to try it out and report back :)

The patch is currently on the `image-converter` branch. If you're installing with pip, you can run

```
pip install --user git+https://github.com/ludvb/xfuse@image-converter
```

Then convert the image using

```
xfuse --debug convert image --image /path/to/image-file --output-file /path/to/output-file.h5
```

Afterwards, just add the output file to the config as an additional slide and you're good to go.

Keep in mind that the trained model may be sensitive to staining variations and other types of differences to the images in the training set. If this turns out to be a problem, it could be valuable to include the unseen sample in the training process or do fine-tuning with the new data. I'm still not 100% sure what the best process is for out-of-sample predictions.

**Comment by ludvb** [comment]
Just to add for clarity: To reuse the trained model when rerunning the analyses, you can use the `--session /path/to/final.session` flag of the `xfuse run` command.

**Comment by theophilefro** [comment]
Hi,

Thanks for your answer. I did the command line :
``` pip install --user git+https://github.com/ludvb/xfuse@image-converter```
But then when I use the convert function I have the error : ```Error: No such command "image".```.
And also what is the role of the ```--debug``` option ?

Thanks,

**Comment by ludvb** [comment]
Thanks for reporting back! My guess would be that the old version is still in your PATH. `pip install --user` typically copies the executable to `~/.local/bin`. Does it work if you run `~/.local/bin/xfuse` instead of `xfuse`? What is the output of `which xfuse`?
