### ISSUE TITLE
The parameter v has invalid values

### ISSUE THREAD

**Issue by jianhuupenn** [ludvb/xfuse#36]
Hi there,
Thanks for providing this nice tool! I was able to run using the sample data you provided, so I suppose the environment is correct.  I have an error when runing XFuse for another ST data. The error message is attached below, could you help me with that? 
```
[2022-02-24 11:58:53,539] INFO : Running xfuse version 0.2.1
[2022-02-24 11:58:53,614] INFO : Using the following design table:
[2022-02-24 11:58:53,614] INFO :
[2022-02-24 11:58:53,615] INFO : | section1 |
[2022-02-24 11:58:53,615] INFO :
[2022-02-24 11:58:54,029] INFO : The following 14382 genes have been filtered out:
....
....
[2022-02-24 11:58:54,037] INFO : Adding metagene: 1
[2022-02-24 11:58:54,038] INFO : Registering experiment: ST (data type: "ST")
[2022-02-24 11:59:06,688] WARNING : RuntimeWarning (/appl/python-3.9/lib/python3.9/site-packages/xfuse/data/utility/misc.py:87): Mean of empty slice.
[2022-02-24 11:59:06,689] WARNING : RuntimeWarning (/appl/python-3.9/lib/python3.9/site-packages/numpy/core/_methods.py:189): invalid value encountered in double_scalars
[2022-02-24 11:59:09,574] ERROR : ValueError: The parameter v has invalid values

```

```
Traceback (most recent call last):
  File "/appl/python-3.9/lib/python3.9/site-packages/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/appl/python-3.9/lib/python3.9/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/appl/python-3.9/lib/python3.9/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)
  File "/appl/python-3.9/lib/python3.9/site-packages/xfuse/model/xfuse.py", line 94, in model
    _go(self.get_experiment(experiment), x)
  File "/appl/python-3.9/lib/python3.9/site-packages/xfuse/model/xfuse.py", line 91, in _go
    experiment.model(x, zs)
  File "/appl/python-3.9/lib/python3.9/site-packages/xfuse/model/experiment/st/st.py", line 372, in model
    Delta(
  File "/appl/python-3.9/lib/python3.9/site-packages/pyro/distributions/distribution.py", line 18, in __call__
    return super().__call__(*args, **kwargs)
  File "/appl/python-3.9/lib/python3.9/site-packages/pyro/distributions/delta.py", line 44, in __init__
    super().__init__(batch_shape, event_shape, validate_args=validate_args)
  File "/appl/python-3.9/lib/python3.9/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter v has invalid values

```

**Comment by ludvb** [comment]
Hi! 

This could be a symptom of a failure in the data conversion step. Can you check if the tissue mask looks good?

```py
import h5py
import matplotlib.pyplot as plt

with h5py.File("/path/to/data.h5") as d:
  mask = d['label'][()] != 1
  he = d['image'][()]

fig, ax = plt.subpots(1, 2)
ax[0].imshow(mask)
ax[1].imshow(he)
fig.show()
```

The result should look something like this:

![image](https://user-images.githubusercontent.com/23262365/155956063-c7e646a8-0758-4449-a415-6f6051385121.png)

If the mask doesn't correspond to the H&E and you are using Visium data, can you try the `improve-visium-masking` branch instead when running `xfuse convert`? It tries to improve masking by making use of the "in_tissue" column in the tissue_positions_list.csv file from space ranger.

**Comment by jianhuupenn** [comment]
Got it, so error comes from the incorrect contour.
