### ISSUE TITLE
Decoding error in data preprocessing

### ISSUE THREAD

**Issue by yunong-xia** [ludvb/xfuse#47]
Hi, 

Is there any way to fix the "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte"?

The following is the complete error message.

`xia00045@ln1002 [~/final_project] % /home/ruping/xia00045/.local/bin/xfuse convert st --counts section1.tsv --image section1.jpg --transformation-matrix section1-alignment.txt --scale 0.15 --save-path section1
[2022-05-08 14:45:33,429] ℹ : Running xfuse version 0.2.1
[2022-05-08 14:45:33,432] 🚨 ERROR : UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/home/ruping/xia00045/.local/lib/python3.8/site-packages/xfuse/__main__.py", line 78, in _wrapped
    return f(*args, **kwargs)
  File "/home/ruping/xia00045/.local/lib/python3.8/site-packages/xfuse/__main__.py", line 244, in _convert_st
    counts_data = pd.read_csv(counts, sep="\t", index_col=0)
  File "/home/ruping/xia00045/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/ruping/xia00045/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ruping/xia00045/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ruping/xia00045/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/ruping/xia00045/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1235, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/ruping/xia00045/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 544, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 633, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1952, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

**Comment by yunong-xia** [comment]
<img width="1680" alt="Screen Shot 2022-05-08 at 2 50 31 PM" src="https://user-images.githubusercontent.com/33441530/167313333-aab57d38-f804-4f19-8fb5-53eb33552a9e.png">
