### ISSUE TITLE
Error when Running with Windows

### ISSUE THREAD

**Issue by mattobny** [ludvb/xfuse#63]
Hello xfuse developers, 

Thanks in advance for this package! I'm looking to utilize xfuse with H&E images to predict expression in Breast Cancer tissue. I created a conda environment to mitigate dependency conflicts and installed using the recommended method, i.e. `pip install --user git+https://github.com/ludvb/xfuse@master`

My specs are as follows:

```
Windows 11 v22H2 OS build 22621.1105, 64bit
conda v22.11.1
python v3.8.16
xfuse v0.2.1 (and all associated dependencies, I'm willing and able to provide if necessary but I will save these for brevity)
```

I attempted the walkthrough run on the README, but unfortunately I was met with the error below. 

```
(xfuse_env) C:\dummy\path> xfuse run my-config.toml --save-path my-run
[2023-01-25 13:41:38,090] ℹ : Running xfuse version 0.2.1
[2023-01-25 13:41:38,122] ℹ : Using the following design table:
[2023-01-25 13:41:38,122] ℹ :
[2023-01-25 13:41:38,122] ℹ : |          |   section {1,2,3,4} |
[2023-01-25 13:41:38,122] ℹ : |----------+---------------------|
[2023-01-25 13:41:38,122] ℹ : | section1 |                   1 |
[2023-01-25 13:41:38,122] ℹ : | section2 |                   2 |
[2023-01-25 13:41:38,122] ℹ : | section3 |                   3 |
[2023-01-25 13:41:38,122] ℹ : | section4 |                   4 |
[2023-01-25 13:41:38,122] ℹ :
[2023-01-25 13:41:38,122] 🚨 ERROR : AttributeError: module 'os' has no attribute 'sched_getaffinity'
Traceback (most recent call last):
  File "C:\Users\matth\anaconda3\envs\xfuse_env\lib\site-packages\xfuse\__main__.py", line 585, in run
    _run(
  File "C:\Users\matth\anaconda3\envs\xfuse_env\lib\site-packages\xfuse\run.py", line 64, in run
    if (available_cores := len(os.sched_getaffinity(0))) < num_data_workers:
AttributeError: module 'os' has no attribute 'sched_getaffinity'
```

I noticed that xfuse had been tested with GNU/Linux on the README, but that other OS should work. I have Ubuntu on my machine, but would prefer to keep this installation in a conda environment. Furthermore, the version of python associated with Ubuntu causes dependency conflicts with torch which cannot be resolved by pip. In any case, I am unsure of how to proceed, and figured you may have come across this error before. I opened this as a new issue because #51 is relevant to mac, but not Windows. Please let me know if there is any other information I can provide to help you in helping me; thank you again!

**Comment by mattobny** [comment]
Turns out the pull request works for Windows OS as well (at least so far).

For others that may experience a similar issue, the following commits were particularly helpful:

https://github.com/ludvb/xfuse/pull/51/commits/616e74c11bf9d90e43e3397720df47df0aa1369b
https://github.com/ludvb/xfuse/pull/51/commits/e99f35e7722112a2d8c6885a02ccc39f08b064c9
https://github.com/ludvb/xfuse/pull/51/commits/2d7535e7c61fbf0248dcaf957222faa3d35b48f6
